apiVersion: v1
kind: Pod
metadata:
  name: mcbrowser
  labels:
    app: mcbrowser
    component: mcbrowser
spec:
  containers:
    - name: mcbrowser
      image: mcbrowser:0.1.0
      ports:
        - containerPort: 80
      imagePullPolicy: Always
      resources:
        limits:
          cpu: '1'
          memory: '512Mi'
        requests:
          cpu: '0.5'