apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcbrowser
  name: mcbrowser
spec:
  ports:
   - port: 8080
     protocol: TCP
     targetPort: 80
  selector:
    app: mcbrowser
  type: LoadBalancer