global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'dotnetruntime'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['mcbrowser:443']
    tls_config:
      insecure_skip_verify: true
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
