name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET 6.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Restore tools
      run: dotnet tool restore
    - name: Clean solution
      run: dotnet nuke Clean
    - name: Build solution
      run: dotnet nuke Compile
    - name: Test solution
      run: dotnet nuke Test
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          test